version: '3.7'
services:
  elasticsearch:
    build: ./es
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch02
      - cluster.initial_master_nodes=elasticsearch,elasticsearch02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_vol:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch02:
    build: ./es
    container_name: elasticsearch02
    environment:
      - node.name=elasticsearch02
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch,elasticsearch02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_02_vol:/usr/share/elasticsearch/data
    networks:
      - esnet

  apm:
    image: docker.elastic.co/apm/apm-server:7.1.1
    container_name: apm
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=elasticsearch:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  elasticsearch_vol:
    driver: local
  elasticsearch_02_vol:
    driver: local

networks:
  esnet:
